#!/bin/bash

# Keymap name
KEYMAP_NAME="my_keymap"

# Generate JSON
qmk c2json \
    -kb zsa/voyager \
    -km "$KEYMAP_NAME" \
    ~/qmk_firmware/keyboards/zsa/voyager/keymaps/"$KEYMAP_NAME"/keymap.c \
    -o keymap.json \
    --no-cpp
