#!/bin/bash

# Keymap name
KEYMAP_NAME="sym_keymap"

# Create symlink
ln -s ~/Source/Symmetra-keyboard-layout/src/ \
    ~/qmk_firmware/keyboards/zsa/voyager/keymaps/"$KEYMAP_NAME"

# Generate JSON
qmk c2json \
    -kb zsa/voyager \
    -km "$KEYMAP_NAME" \
    ~/qmk_firmware/keyboards/zsa/voyager/keymaps/"$KEYMAP_NAME"/keymap.c \
    -o keymap.json \
    --no-cpp

# Destroy symlink
rm ~/qmk_firmware/keyboards/zsa/voyager/keymaps/"$KEYMAP_NAME"

