#undef TAPPING_TERM
#define TAPPING_TERM 250

#define PERMISSIVE_HOLD

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_WHEEL_INTERVAL
#define MOUSEKEY_WHEEL_INTERVAL 120

#undef MOUSEKEY_WHEEL_MAX_SPEED
#define MOUSEKEY_WHEEL_MAX_SPEED 6

#define CAPS_LOCK_STATUS
#define SERIAL_NUMBER "7yA5b/pj7pxW"
#define LAYER_STATE_16BIT

#define RGB_MATRIX_STARTUP_SPD 60

